version: '2'

services:
  drone-server:
    image: drone/drone:0.8

    ports:
      - 8090:8000
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
#    Drone 默认是关闭注册的。这个例子开放了指定 GitHub 组织的成员的开放注册：
      - DRONE_OPEN=true
     # - DRONE_ORGS=dolores,dogpatch
      # 管理员账号，多个用逗号分隔，某些项目配置只有管理员账号可以设置(比如设置“Project Settings”为“Trusted”)
      - DRONE_ADMIN=qwkxq
      - DRONE_HOST=http://pengqi.51vip.biz
      - DRONE_SECRET=qwkxq_cqmygysdss
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=1373f6acaa4a1aaf2ab4
      - DRONE_GITHUB_SECRET=468a1a450ece21a333589c2492b236824d34cc9f
      # 这里设置为true否则会报错“Insufficient privileges to use privileged mode”
      - DRONE_GITHUB_PRIVATE_MODE=true

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=qwkxq_cqmygysdss